### ISSUE TITLE
语言

### ISSUE THREAD

**Issue by ERR1024** [MemFaceGo/Better-Blocks-Mod#2]
我需要ZH_CN的语言，如果需要我帮助翻译，请在discord上回复我（ERR!#1680）

**Comment by ERR1024** [comment]
同时，我想了解一下你们MOD的许可协议
由于自述文件没有，所以我需要问

**Comment by MemFaceGo** [comment]
我不介意翻译……但我可以在一天之内提供该文件。 至于许可协议，我没有它，我什至不知道它是必需的。

**Comment by ERR1024** [comment]
请通过discord给我一份txt格式的语言文件（一边是原名，另一边我填写翻译），让我更方便的翻译这个MOD的ZH_CN

**Comment by MemFaceGo** [comment]
好吧，更确切地说，不是.txt格式，而是.properties，好的，您可以等待5-10分钟

**Comment by MemFaceGo** [comment]
抱歉，我现在无法提供文件

**Comment by ERR1024** [comment]
那么，什么时候可以哪？

**Comment by MemFaceGo** [comment]
明天，或者几天后

**Comment by MemFaceGo** [comment]
如果您急需翻译，可以复制俄语翻译并在mod文件中查找块名称

**Comment by ERR1024** [comment]
好的，我需要一个英文的语言文件，这可以让我更方便的翻译

**Comment by MemFaceGo** [comment]
我只能在11月11日做

**Comment by ERR1024** [comment]
请问我翻译ZH_CN所需要的英文语言文件好了吗？
