### ISSUE TITLE
get a better spriter and dont steal sprites.

### ISSUE THREAD

**Issue by notMEEPoffaith** [MemFaceGo/Better-Blocks-Mod#20]
you fucking retard you stole sprites/recolored sprites from commanblocks, exotic mod, pixelcraft, POSSIBLY HAI, a v5 mod, and others.

Go fuck yourself until you fix these big fucking signs of being retarded.

**Comment by notMEEPoffaith** [comment]
just do it

**Comment by MemFaceGo** [comment]
...
